version: "3"

services:
  selenium-chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"

  selenium-firefox:
    image: seleniarm/standalone-firefox:latest
    ports:
      - "4445:4444"

